name: Continuous integration
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up OCaml
        uses: avsm/setup-ocaml@v1.0
