name: Continuous integration
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: OCaml setup
        uses: avsm/setup-ocaml@v1.0
      - name: OPAM repositories
        run: |
          opam repo add coq-released https://coq.inria.fr/opam/released
          opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
      - name: OPAM dependencies (Coq 8.11)
        run: |
          opam install --yes coq.8.11.1
          opam install --yes coq-mathcomp-ssreflect.1.9.0
          opam install --yes coq-mathcomp-fingroup.1.9.0
          opam install --yes coq-mathcomp-algebra.1.9.0
          opam install --yes coq-void.0.1.0
          opam install --yes coq-extructures.dev
          opam install --yes coq-deriving.dev
          opam install --yes coq-quickchick.8.11.dev
      - name: Coq Utils checkout (Coq 8.11)
        uses: actions/checkout@v2
        with:
          repository: arthuraa/coq-utils
          ref: 504aa4285d631b166ae36e0f40a3a8f77cbde224
          path: coq-utils
      - name: Coq Utils build (Coq 8.11)
        run: |
          cd coq-utils
          make
          cd ..
